add user profile support and bump to 2.3.0
estroBiologist/pluralchum pull request #44
Opened 2024-05-22 21:23 UTC by 0xeac7

please suggest any additions to the code or things to be changed. thank you!

2024-05-23 06:30 UTC, ariagivens commented
Thanks for the PR! I haven't had a chance to look at the code yet but heres some notes after clicking around:

## Bugs
When you generate a profile popup by clicking on a name instead a profile picture, it doesn't go away when you click away.
Sometimes profiles show up totally blank.
Console gets spammed with:
```
[BetterDiscord] [Patcher] Could not fire instead callback of getUser for Pluralchum TypeError: Cannot read properties of undefined (reading 'avatarDecorationData')
```

## Changes
A few changes to make it look and work more like profile popup in regular discord.

Take the link underline color from the username color instead of white.
The display name part of the popup (big one at top) should look how it does in the server. The username part (the smaller, lower part) was the base account name.

## Nice to haves but maybe hard to implement??
Showing base account roles?
Either getting rid of the "note" section or using the note from the base account?

2024-05-24 08:50 UTC, ariagivens requested changes
Just a few things that need to be looked at and we should be good to merge!

2024-05-24 08:50 UTC, ariagivens commented on src/profiles.js
> +export function patchProfileBanners() {
patchProfileBanners function belongs in its own file like profilePopout.js or something. profiles.js should just have the code for creating and managing the `profile` object.

2024-05-24 08:50 UTC, ariagivens commented on src/components/ColorMessageHeader.js
> +function PopoutContainer({ message, profileMap, profile, originalProps, tagProps, children }) {
should this be its own component in its own file?

2024-05-24 08:50 UTC, ariagivens commented on src/components/MessageHeaderProxy.js
> +  BdApi.Patcher.instead(pluginName, Components.Popout.prototype, 'render', function (ctx, [props], f) {
Patching inside of a react component seems concerning!

2024-05-24 08:50 UTC, ariagivens commented on src/messages.js
> +  BdApi.Patcher.instead(pluginName, MessageHeader, "default", function (ctx, [props], f) {
Nice!

2024-05-24 08:50 UTC, ariagivens commented on src/profiles.js
> +    color: '#' + (data.member.color || 'ffffff'),
Defaulting to white here seems incorrect to me. Doesn't that break the existing color logic of memberColour and tagColour in ColorMessageHeader.js

2024-05-24 08:50 UTC, ariagivens commented on src/profiles.js
> +    raw: data,
`raw` seems like code smell. It makes it unclear which parts of the PK API we are actually using.

2024-05-24 08:50 UTC, ariagivens commented on src/profiles.js
> +    // console.log("[*] UserProfile:", ret, props, children);
left over debug comment

2024-05-24 08:50 UTC, ariagivens commented on src/profiles.js
> +    // console.log("[*] UserProfileTag:", ret, props, children);
left over debug comment

2024-05-25 22:12 UTC, ariagivens commented
> also - since this is a big update, would it be better to bump the version higher?

we roughly follow [semver](https://semver.org/)

2024-10-19 04:22 UTC, Undeemiss commented
Any updates on this? Is the "color bit" an important unfinished change? I would be willing to try my hand at fixing it if this pull request has been abandoned.

2025-03-16 19:43 UTC, ariagivens commented
Implemented in 2.4.0

2025-03-16 19:43 UTC, closed without merging